version: '3'

services:
  nginx:
    image: docker.io/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tomcat

  tomcat:
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
      - ./tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml:ro
      - ./tomcat/context.xml:/usr/local/tomcat/webapps/host-manager/META-INF/context.xml:ro
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=logindb
      - MYSQL_USER=loginuser
      - MYSQL_PASSWORD=loginpass

  mysql:
    image: docker.io/mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=logindb
      - MYSQL_USER=loginuser
      - MYSQL_PASSWORD=loginpass
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
